ARG  DIST=nginx:1.21.3
FROM $DIST

ARG DOMAIN="lvh.me"

RUN apt update && apt install -y certbot vim

COPY nginx/default.conf /etc/nginx/conf.d/default.conf
RUN sed -i -e "s/__DOMAIN__/$DOMAIN/g" /etc/nginx/conf.d/default.conf
